import tkinter as tk
 
window = tk.Tk()
button1 = tk.Button(text="1",width=25,
    height=5,
    bg="blue",
    fg="yellow",)
button2 = tk.Button(text="2")
button3 = tk.Button(text="3")
button4 = tk.Button(text="4")
button5 = tk.Button(text="5")
button6 = tk.Button(text="6")
button7 = tk.Button(text="7")
button8 = tk.Button(text="8")
button9 = tk.Button(text="9")
button10 = tk.Button(text="0")
button11 = tk.Button(text="+")
button12 = tk.Button(text="-")
button13 = tk.Button(text="/")
button14 = tk.Button(text="*")
button15 = tk.Button(text="=")
button16 = tk.Button(text="!!")
button1.pack()
button2.pack()
button3.pack()
button4.pack() 
button5.pack()
button6.pack()
button7.pack()
button8.pack() 
button9.pack()
button10.pack()
button11.pack()
button12.pack() 
button13.pack()
button14.pack()
button15.pack()
button16.pack() 
window.mainloop()
      
