import tkinter as tk
 
window = tk.Tk()
entry=tk.Entry()
button1 = tk.Button(text="1",width=2,
    height=1,
    bg="lightblue",
    fg="red",)
button2 = tk.Button(text="2")
button3 = tk.Button(text="3")
button4 = tk.Button(text="4")
button5 = tk.Button(text="5")
button6 = tk.Button(text="6")
button7 = tk.Button(text="7")
button8 = tk.Button(text="8")
button9 = tk.Button(text="9")
button10 = tk.Button(text="0")
button11 = tk.Button(text="+")
button12 = tk.Button(text="-")
button13 = tk.Button(text="/")
button14 = tk.Button(text="*")
button15 = tk.Button(text="=")
button16 = tk.Button(text="!!")
button1.pack()
button2.pack()
button3.pack()
button4.pack() 
button5.pack()
button6.pack()
button7.pack()
button8.pack() 
button9.pack()
button10.pack()
button11.pack()
button12.pack() 
button13.pack()
button14.pack()
button15.pack()
button16.pack() 
button1.grid(row=0, column=0)
button1.grid(row=0, column=1)
button1.grid(row=0, column=2)
button1.grid(row=1, column=0)
button1.grid(row=1, column=1)
button1.grid(row=1, column=2)
button1.grid(row=2, column=0)
button1.grid(row=2, column=1)
button1.grid(row=2, column=1)
button1.grid(row=3, column=0)
button1.grid(row=3, column=1)
button1.grid(row=3, column=2)
button1.grid(row=4, column=0)
button1.grid(row=4, column=1)
button1.grid(row=4, column=2)
button1.grid(row=5, column=1)
window.mainloop()
      
